CREATE TABLE clientes (
  CODIGO_CLIENTE varchar(255) NOT NULL primary key,
  EMPRESA varchar(255) DEFAULT NULL ,
  DIRECCION varchar(255) DEFAULT NULL,
  POBLACION varchar(255) DEFAULT NULL,
  TELEFONO number(9) DEFAULT NULL,
  RESPONSABLE varchar(255) DEFAULT NULL,
  HISTORIAL varchar(255) DEFAULT NULL,
  CONSTRAINT unico UNIQUE (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL)

)
