CREATE TABLE clientes (
  CODIGO_CLIENTE varchar(255) NOT NULL primary key,
  EMPRESA varchar(255) DEFAULT NULL ,
  DIRECCION varchar(255) DEFAULT NULL,
  POBLACION varchar(255) DEFAULT NULL,
  TELEFONO int(9) DEFAULT NULL,
  RESPONSABLE varchar(255) DEFAULT NULL,
  HISTORIAL varchar(255) DEFAULT NULL,
  CONSTRAINT unico UNIQUE (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL)

);


INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT01', 'BELTRAN E HIJOS', 'LAS FUENTES 78', 'MADRID', 914456435, 'ANGEL MARTINEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT02', 'LA MODERNA', 'LA PALOMA 123', 'OVIEDO', 985323434, 'JUAN GARCIA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT03', 'EL CASTELLANO', 'MOTORES 34', 'BARCELONA', 934565343, 'ANA FERNANDEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT04', 'EXPORTASA', 'VALLECAS 34', 'MADRID', 913452378, 'ELVIRA GOMEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT06', 'CONFECCIONES AMPARO', 'LOS MOROS 23', 'GIJON', 985754332, 'LUIS ALVAREZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT07', 'LA CASA DEL JUGUETE', 'AMERICA 45', 'MADRID', 912649987, 'ELIAS PEREZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT08', 'JUGUETERIA SUAREZ', 'PARIS 123', 'BARCELONA', 933457866, 'JUAN GARCIA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT09', 'ALMACEN POPULAR', 'LAS FUENTES 124', 'BILBAO', 942347127, 'JOSE ALVAREZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT10', 'FERETERIA EL CLAVO', 'PASEO DE ALAMOS 78', 'MADRID', 914354866, 'MANUEL MENENDEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT11', 'JUGUETES MARTINEZ', 'VIA LAYETANA 245', 'BARCELONA', 936628554, 'FRANCISCO CUEVAS', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT12', 'FERNANDEZ SL', 'PASEO DEL MAR 45', 'SANTANDER', 942049586, 'ELISA COLLADO', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT13', 'CONFECCIONES ARTIMEZ', 'GENERAL PERON 45', 'A CORUÑA', 981345239, 'ESTEBAN PASCUAL', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT14', 'DEPORTES GARCIA', 'GUZMAN EL BUENO 45', 'MADRID', 913299475, 'ANA JIMENEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT15', 'EXCLUSIVAS FERNANDEZ', 'LLOBREGAT 250', 'BARCELONA', 939558365, 'LUISA FERNANDEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT16', 'DEPORTES MORAN', 'AUTONOMIA 45', 'LUGO', 982986944, 'JOSE MANZANO', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT17', 'BAZAR FRANCISCO', 'CARMEN 45', 'ZAMORA', 980495288, 'CARLOS BELTRAN', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT18', 'JUGUETES LA SONRISA', 'LA BANEZA 67', 'LEON', 987945368, 'FAUSTINO PEREZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT19', 'CONFECCIONES GALAN', 'FUENCARRAL 78', 'MADRID', 913859234, 'JUAN GARCIA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT20', 'LA CURTIDORA', 'OLIVARES 3', 'MALAGA', 953756259, 'MARIA GOMEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT21', 'LINEA JOVEN', 'SIERPES 78', 'SEVILLA', 953452567, 'ASUNCION SALADO', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT22', 'BAZAR EL BARAT', 'DIAGONAL 56', 'BARCELONA', 936692866, 'ELISA DAPENA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT23', 'EL PALACIO DE LA MODA', 'ORTEGA Y GASSET 129', 'MADRID', 927785235, 'LAURA CARRASCO', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT24', 'SAEZ Y CIA', 'INFANTA MERCEDS 23', 'SEVILLA', 954869234, 'MANUEL GUERRA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT25', 'DEPORTES EL MADRID', 'CASTILLA 345', 'ZARAGOZA', 976388934, 'CARLOS GONZALEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT26', 'FERRETERIA LA ESCOBA', 'ORENSE 7', 'MADRID', 918459346, 'JOSE GARCIA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT27', 'JUGUETES EL BARATO', 'VIA AUGUSTA 245', 'BARCELONA', 933486984, 'ELVIRA IGLESIAS', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT28', 'CONFECCIONES HERMINIA', 'CORRIDA 345', 'GIJON', 985597315, 'ABEL GONZALEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT30', 'BAZAR EL ARGENTINO', 'ATOCHA 55', 'MADRID', 912495973, 'ADRIAN ALVAREZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT31', 'LA TIENDA ELEGANTE', 'EL COMENDADOR 67', 'ZARAGOZA', 975694035, 'JOSE PASCUAL', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT32', 'DEPORTES NAUTICOS GARCIA', 'JUAN FERNANDEZ 89', 'AVILA', 920268648, 'JUAN CONRADO', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT33', 'CONFECCIONES RUIZ', 'LLOBREGAT 345', 'BARCELONA', 934587615, 'CARLOS SANZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT34', 'BAZAR LA FARAONA', 'CASTILLA Y LEON 34', 'MADRID', 915483627, 'ANGEL SANTAMARIA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT35', 'FERRETERIA EL MARTILLO', 'CASTELLANOS 205', 'SALAMANCA', 923548965, 'JOAQUIN FERNANDEZ', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT36', 'JUGUETES EDUCATIVOS SANZ', 'ORENSE 89', 'MADRID', 916872354, 'PEDRO IGLESIAS', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT37', 'ALMACENES FERNANDEZ', 'ANTON 67', 'TERUEL', 978564025, 'MARIA ARDANZA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT38', 'CONFECCIONES MONICA', 'MOTORES 67', 'BARCELONA', 935681245, 'PEDRO SERRANO', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT39', 'FERRETERIA LIMA', 'VALLECAS 45', 'MADRID', 913532785, 'LUIS GARCIA', NULL);
INSERT INTO clientes (CODIGO_CLIENTE, EMPRESA, DIRECCION, POBLACION, TELEFONO, RESPONSABLE, HISTORIAL) VALUES
('CT40', 'DEPORTES BRASIL', 'ABEL MARTINEZ 67', 'SALAMANCA', 921548762, 'CARLOS GOMEZ', NULL);
